### PR TITLE
Add `curl getcaddy.com | bash`

### PR DESCRIPTION
**Pull request by coolaj86**

### CODE REVIEW

**Comment by mholt** [comment]
Nice. I'm gonna wait until getcaddy.com is over HTTPS with Let's Encrypt, then I'll work on merging this in... it'll probably be a while before the new site design is ready anyway.

**Comment by casdr** [comment]
https://www.seancassidy.me/dont-pipe-to-your-shell.html

**Comment by coolaj86** [comment]
Piping to your shell is no less secure than installing a .deb or .pkg or .exe.

Don't talk to strangers

Don't tell secrets

Don't have unprotected sex

Don't pipe to the shell

All of these warnings deal with social problems. The root problem is this:

**don't trust people you don't trust!**

As long as you trust the other party, none of those rules apply.

We trust us. Period.

**Comment by coolaj86** [comment]
(Also, we don't rm)

**Comment by coolaj86** [comment]
Also, I think the chances of your cat typing 'rm -rf' are greater than that of a 64k packet ending in it.

A good caution would be to have the piped script to download the installer script to run local.

**Comment by casdr** [comment]
Both of those are correct, rm isn't the only problem though. If getcaddy.com can indeed be fully trusted, it's okay, I have no idea who is behind this site though (are you the one?) , so that's why I just wanted to leave it here :)

**Comment by coolaj86** [comment]
@mholt runs the site and owns Caddy. Digital Ocean provides the hosting. Caddy is the server.

**Comment by casdr** [comment]
@coolaj86 I thought it was someone from the community, case closed :)

**Comment by mholt** [comment]
I run getcaddy.com. :wink: The original script comes from @coolaj86 who did a fantastic job making it work a lot better than the piece of hobbled-together junk I had before! Anyway, sure, we could probably download the script as a separate file and run it locally after performing checksums and yada yada, but frankly it's not a huge priority for me right now.

**Comment by coolaj86** [comment]
It never got merged into the main site https://caddyserver.com/download

:'( Oh well.

And it does like we do `rm -rf /tmp` after all... but it is just the tmp dir and the script is under 64k, so I'm not worried about it.

**Comment by mholt** [comment]
It will be on the next version of the site! We're working on it. ;)

**Comment by mholt** [comment]
@coolaj86 This has been implemented on the new site. Thank you!

**Pull request closed without merging**
