### PR TITLE
Adding docs for real-ip module. Trying markdown.

### PR DESCRIPTION
**Pull request by captncraig**
Wanted to see how markdown works. This certainly feels more natural than hand coding all of the html. Has a common docs template that only requires a few fields in front matter.

The only thing not working super great is the formatting on the code snippets. Perhaps some kind of javascript highlighting could be adapted, but I'm not sure how much of a dealbreaker that would be.

### CODE REVIEW

**Comment by captncraig** [comment]
This isn't ready to merge yet. Still need to harden up the tests and things and add it to buildsrv as well. But I wanted to start the discussion about md up front.

**Comment by mholt** [comment]
@captncraig Could you fix the merge conflict and then I will merge it in :)

**Comment by captncraig** [comment]
@mholt I updated, rebased, added some features, and it should be ready to go.

Interested to see how easily old docs convert to md.

**Comment by mholt** [comment]
Hey this is pretty cool. I'll merge it in, and I might smooth out any rough edges, but so far I like this! Thanks!

**Pull request merged**
