### PR TITLE
Update ratelimit plugin docs

### PR DESCRIPTION
**Pull request by xuqingfeng**
For supporting `time unit` feature.

### CODE REVIEW

**Comment by mholt** [comment]
Cool, thanks.

Why not use the standard time.Duration format? E.g. `2m` or `2s`. time.ParseDuration() can do this.

**Comment by xuqingfeng** [comment]
@mholt you mean change `second`->`s`, `minute`->`m`, `hour`->`h` ?

**Comment by mholt** [comment]
I mean make the duration argument not just a number but also include a unit so you don't need the third argument. So instead of `2`, it would be `2s` for example.

**Comment by xuqingfeng** [comment]
@mholt but `2s` doesn't make sense for `rate`, right?

**Comment by mholt** [comment]
Ah, you mean it's like "2 per second"?

**Comment by xuqingfeng** [comment]
@mholt yeah 😄

**Comment by mholt** [comment]
I see. Well, it could be read as "Expire tokens after 2s" or something like that. But anyway, just a thought. I guess it's fine as-is too.

**Pull request merged**
