### PR TITLE
Add features for `curl getcaddy.com | bash -s git,search`

### PR DESCRIPTION
**Pull request by coolaj86**
Makes it so you can copy and paste the proper curl command.

### CODE REVIEW

**Comment by kevinsimper** [comment]
@coolaj86 How would curl execute javascript?

**Comment by mholt** [comment]
@kevinsimper  It doesn't. Why does it need to?

**Comment by kevinsimper** [comment]
Thought this was getting features with curl, but I now understand with the lack of description that it changes the html on the page that you have to copy and paste 😅

**Comment by mholt** [comment]
Implemented on the new site -- thank you very much!

**Pull request closed without merging**
